/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;
import org.apache.struts.actions.DispatchAction;

import com.apl.sha.ers.Processing;
import com.apl.sha.ers.model.News;
import com.apl.sha.ers.model.User;
import com.apl.sha.ers.struts.form.AdminBulletinForm;
import com.apl.sha.ers.util.BeanUtil;
import com.apl.sha.ers.util.DateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 08-20-2007
 * 
 * XDoclet definition:
 * @struts.action path="/adminBulletin" name="adminBulletinForm" input="/adminBulletin.jsp" parameter="method" scope="request" validate="true"
 * @struts.action-forward name="success" path="/adminBulletin.jsp"
 */
public class AdminBulletinAction extends DispatchAction {
	protected Processing process;
	
	public Processing getProcess() {
		return process;
	}
	
	public void setProcess(Processing process) {
		this.process = process;
	}
	/*
	 * Generated Methods
	 */
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward get(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		List newses=process.getNewses();
		request.getSession().setAttribute("allNewses",newses);
		return mapping.findForward("success");
	}
	public ActionForward add(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminBulletinForm adminBulletinForm = (AdminBulletinForm) form;
		News news=new News();
		User user=(User)request.getSession().getAttribute("user");
		BeanUtil.copyProperties(adminBulletinForm, news);
		news.setBegDate(DateUtil.parseDate(adminBulletinForm.getBegDate()));
		news.setEndDate(DateUtil.parseDate(adminBulletinForm.getEndDate()));
		process.setNews(news, user);
		return get(mapping, adminBulletinForm, request, response);
	}
	public ActionForward delete(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		int id=Integer.parseInt(request.getParameter("id"));
		process.delNews(id);
		ActionMessages messages=new ActionMessages();
		messages.add("delNewsMSG",new ActionMessage("message.success.displayname"));
		this.addMessages(request, messages);
//		News news=new AdminBulletinAction
//		BeanUtil.copyProperties(adminBulletinForm, request)
		return get(mapping, form, request, response);
	}
}