/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.apl.sha.ers.model.User;

/** 
 * MyEclipse Struts
 * Creation date: 05-24-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/home.jsp" redirect="true"
 */
public class DelBookingAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ActionForward actionForward=this.checkPriv(mapping, request, this.getClass().getSimpleName());
		if(actionForward!=null) return actionForward ;
		int blnumber=Integer.parseInt(request.getParameter("blnumber"));
		User user=this.getUser(request);
		ActionMessages messages=new ActionMessages();
		if(process.delBooking(blnumber,user)) {
			messages.add("delBookingMSG",new ActionMessage("message.success.displayname"));			
		}else {
			messages.add("delBookingMSG",new ActionMessage("error.object.notfound", new Object[] {getMessage(request, "booking.displayname"),blnumber}));			
		}
		this.addMessages(request, messages);
		return mapping.findForward(success);
	}
}