/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.apl.sha.ers.model.OneWayCtn;
import com.apl.sha.ers.model.User;

/** 
 * MyEclipse Struts
 * Creation date: 01-15-2008
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/getOneWayCtns.jsp"
 */
public class DistributionDepotAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	
	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
//		ActionForward actionForward=this.checkPriv(mapping, request, this.getClass().getSimpleName());
//		if(actionForward!=null) return actionForward ;
		int blnumber = 0;
		try {
			blnumber=Integer.parseInt(request.getParameter("blnumber").trim());
		}catch(NumberFormatException e) {
			System.out.println("blnumber exception......."+e.getMessage());
		}
		process.distributionDepot(blnumber);
		return mapping.findForward("success");
	}
	
}