/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.apl.sha.ers.exception.LoginException;

/** 
 * MyEclipse Struts
 * Creation date: 04-18-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/adminAccount.jsp"
 */
public class GetAccountAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String username=request.getParameter("username");
		try {
			process.getUser(username, username, false);
		} catch (LoginException e) {
//			int errCode=e.getStatus();
//			errorHandle(mapping, request, "error.account.not")
//			errors.add("loginfail", new ActionMessage("error.login.nouser"));
		}
		return mapping.findForward(success);
	}
}