/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.apl.sha.ers.model.User;

/** 
 * MyEclipse Struts
 * Creation date: 03-15-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/getBookingCtnGroups.jsp"
 */
public class GetBookingCtnGroupsAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ActionForward actionForward=this.checkPriv(mapping, request, this.getClass().getSimpleName());
		if(actionForward!=null) return actionForward ;
		int days=5;
		try {
			days=Integer.parseInt(request.getParameter("days"));
		} catch (NumberFormatException e) {
		}
		String vessel=request.getParameter("vessel").toUpperCase().trim();
		User user=getUser(request);
		HttpSession session=request.getSession();
		session.setAttribute("bookingctngroups", process.getBookingCtnGroups(days,vessel, user));
		return mapping.findForward(success);
	}
}