/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.apl.sha.ers.model.Paging;
import com.apl.sha.ers.model.User;

/** 
 * MyEclipse Struts
 * Creation date: 03-09-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/getBookings.jsp"
 */
public class GetBookingsAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ActionForward actionForward=this.checkPriv(mapping, request, this.getClass().getSimpleName());
		if(actionForward!=null) return actionForward ;
		int page=1;
		int size=20;
		int days=30;
		try {
			page=Integer.parseInt(request.getParameter("page"));
		} catch (NumberFormatException e1) {
		}
		try {
			size=Integer.parseInt(request.getParameter("size"));
		} catch (NumberFormatException e) {
		}
		try {
			days=Integer.parseInt(request.getParameter("days"));
		} catch (NumberFormatException e) {
		}
		String vessel=request.getParameter("vessel").toUpperCase().trim();
		String dest=request.getParameter("dest").toUpperCase().trim() ;
		User user=getUser(request);
		Paging paging=new Paging();
		paging.setPage(page);
		paging.setSize(size);
		HttpSession session=request.getSession();
		List bookings=process.getBookings(paging, days,vessel,dest, user);
		session.setAttribute("bookings", bookings);
//		List bookingCtns=process.getBookingCtns(bookings, user);
//		session.setAttribute("bookingsCtns", bookingCtns);
		paging.setTotal(process.getBookings(days,vessel,dest, user));
		session.setAttribute("paging", paging);
		return mapping.findForward(success);
	}
}