/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import java.io.UnsupportedEncodingException;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.apl.sha.ers.exception.BookingException;
import com.apl.sha.ers.exception.ErrCode;
import com.apl.sha.ers.exception.NoDataException;
import com.apl.sha.ers.model.User;

/** 
 * MyEclipse Struts
 * Creation date: 12-26-2006
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/getbooking.jsp"
 */
public class GetCtnReleaseAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 * @throws UnsupportedEncodingException 
	 * @throws Throwable 
	 * @throws NoDataException 
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) throws UnsupportedEncodingException {
		ActionForward actionForward=this.checkPriv(mapping, request, this.getClass().getSimpleName());
		if(actionForward!=null) return actionForward ;
		int blnumber=0;
		String cuser="";
		
		try {
			blnumber=Integer.parseInt(request.getParameter("blnumber").trim());
		}catch(NumberFormatException e) {
			return this.errorHandle(mapping, request, "errors.integer",new Object[] {"Booking"});
		}
		cuser=request.getParameter("cuser").trim();
		HttpSession session=request.getSession();
		//Map ctnTypes=(Map)session.getServletContext().getAttribute("ctntypes");
		String templateFolder=session.getServletContext().getRealPath("/report");
		String destFileName="GetCtnRelease"+blnumber+".html";
		String destFilePath=session.getServletContext().getRealPath("/report/"+destFileName);
/*		try {
			session.setAttribute("booking", process.getBooking(blnumber,ctnTypes));
		} catch (NoDataException e) {
			return this.errorHandle(mapping, request, "error.object.notfound", new Object[] {"Booking",blnumber});
		}*/
		User user=getUser(request);
		//String dusername=user.getUsername();
		//String returnLink=request.getHeader("Referer");
		try {
			process.GetCtnRelease(templateFolder, destFilePath, blnumber, cuser, user);
		} catch (NoDataException e) {
			return this.errorHandle(mapping, request, "error.object.notfound", new Object[] {getMessage(request, "booking.displayname"),blnumber});
		} catch (BookingException e) {
			if(e.getErrCode()==ErrCode.notOwnerBookingCode) {
				return this.errorHandle(mapping, request, "error.booking.notowner", new Object[] {blnumber});
			}
		}
		session.setAttribute("path", "/report/"+destFileName);
		return new ActionForward("/report/"+destFileName,true);
//		return new ActionForward("/getBookingOrder.jsp",true);
	}
}