/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.apl.sha.ers.exception.DataException;
import com.apl.sha.ers.model.User;

/** 
 * MyEclipse Struts
 * Creation date: 01-08-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/getDepots"
 */
public class GetDepotsAction extends BaseAction {
	private static final String privname="GetDepotAction";
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ActionForward actionForward=this.checkPriv(mapping, request, privname);
		if(actionForward!=null) return actionForward ;
		HttpSession session=request.getSession();
		User user=(User)session.getAttribute("user");
		try {
			session.setAttribute("depots", process.getDepots(user.getLocation()));
		} catch (DataException e) {
			return this.errorHandle(mapping, request, "error.object.notfound", new Object[] {"Depot"});
		}
		return mapping.findForward(success);
	}
}