/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import java.util.Calendar;
import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;

import com.apl.sha.ers.model.User;
import com.apl.sha.ers.util.DateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/adminSystem.jsp"
 */
public class GetLogsAction extends BaseAction {
	private static final String datePattern="yyyy-MM-dd";
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Date begDate=DateUtil.parseDate(request.getParameter("begDate"),datePattern);
		Date endDate=DateUtil.parseDate(request.getParameter("endDate"),datePattern);
		ActionErrors errors=new ActionErrors();
		if(begDate==null) {
			errors.add("begDate",new ActionMessage("errors.date",getMessage(request, "keywords.begDate"),datePattern));
		}/*else {
			Calendar calendar=Calendar.getInstance();
			calendar.setTime(begDate);
//			calendar.add(Calendar.DATE,-1);
			begDate=calendar.getTime();
		}*/
		if(endDate==null) {
			endDate=new Date();
//			errors.add("endDate",new ActionMessage("errors.date",getMessage(request, "keywords.endDate"),datePattern));
		}
		if(errors.size()>0) {
			this.addErrors(request, errors);
			request.getSession().removeAttribute("logs");
			return mapping.getInputForward();
		}
		int userID=0;
		try {
			userID=Integer.parseInt(request.getParameter("userid"));
		} catch (NumberFormatException e) {
		}
		String type=request.getParameter("type");
		String function=request.getParameter("function");
		User user=getUser(request);
		request.getSession().setAttribute("logs",process.getLogs(begDate, endDate, type,function, userID, user));
		return mapping.findForward(success);
	}
}