/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.apl.sha.ers.exception.DataException;
import com.apl.sha.ers.model.User;
import com.apl.sha.ers.struts.form.SetUserForm;
import com.apl.sha.ers.util.BeanUtil;

/** 
 * MyEclipse Struts
 * Creation date: 01-24-2007
 * 
 * XDoclet definition:
 * @struts.action path="/setUser" name="setUserForm" input="/setUser.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/account.jsp"
 */
public class SetAccountAction extends BaseAction {
	private static final String cancelPath="/home.jsp";
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(isCancelled(request)) {
			return cancelHandle(mapping,request,cancelPath);
		}
		User curUser=getUser(request);
		SetUserForm setUserForm = (SetUserForm) form;
		
		User user=(User)BeanUtil.cloneBean(curUser);
		convertFromForm(setUserForm,user);
		try {
			user=process.setUser(user,user);
		} catch (DataException e) {
		}
		request.getSession(false).setAttribute("user", user);
		return mapping.findForward(success);
	}
	private User convertFromForm(SetUserForm form,User user) {
		user.setPwd(form.getPwd());
		user.setTitle(form.getTitle());
		user.setEmail(form.getEmail());
		user.setLocale(form.getLocale());
		return user;
	}
}