/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.apl.sha.ers.exception.NonUniqueDataException;
import com.apl.sha.ers.model.CtnType;
import com.apl.sha.ers.model.BlockCodeUpdate;
import com.apl.sha.ers.model.User;
import com.apl.sha.ers.struts.form.SetBookingInfoForm;


public class SetBookingInfoAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {

		ActionForward actionForward=this.checkPriv(mapping, request, this.getClass().getSimpleName());
		if(actionForward!=null) return actionForward ;
		User user=this.getUser(request);
		SetBookingInfoForm biForm=(SetBookingInfoForm) form;
		String block_code = biForm.getSetBI_blockcode().toUpperCase();
		int blnumber = biForm.getSetBI_blnumber();
		process.setBookingInfo(block_code, blnumber, user);
		ActionMessages messages=new ActionMessages();
		messages.add("setBookingInfoMSG",new ActionMessage("message.success.displayname"));
		this.saveMessages(request, messages);
		return mapping.findForward(success);
	}

}