/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.apl.sha.ers.model.User;

/** 
 * MyEclipse Struts
 * Creation date: 06-26-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="/booking.jsp"
 */
public class SetCtnStatusforAmendAction extends BaseAction {
	private static final String privname="SetCtnStatusforAmendAction";
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ActionForward actionForward=this.checkPriv(mapping, request, privname);
		if(actionForward!=null) return actionForward ;
		int blnumber=Integer.parseInt(request.getParameter("blnumber").trim());
		User user=(User) request.getSession().getAttribute("user");
		ActionMessages messages=new ActionMessages();
		if(process.setCtnStatusforAmend(blnumber, user)>0) {
			messages.add("ChangeCtnStatusMSG",new ActionMessage("message.success.displayname"));			
		}else {
			messages.add("ChangeCtnStatusMSG",new ActionMessage("error.cstatusctn.notfound"));			
		}
		this.saveMessages(request, messages);
		return mapping.findForward(success);
	}
}