/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.apl.sha.ers.struts.form.SetVslVoyForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-17-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="booking.jsp"
 */
public class SetVslVoyAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(isCancelled(request)) {
			return cancelHandle(mapping,request,null);
		}
		ActionForward actionForward=this.checkPriv(mapping, request, this.getClass().getSimpleName());
		if(actionForward!=null) return actionForward ;
		SetVslVoyForm setVslVoyForm=(SetVslVoyForm) form;
		int blnumber = Integer.parseInt(setVslVoyForm.getVblnumber());
		ActionMessages messages=new ActionMessages();
		ActionErrors errors = new ActionErrors();
		if(process.checkVessel(setVslVoyForm.getVslcd())== 0 ){
			errors.add("setVslVoyError", new ActionMessage("error.setvslvoy.novessel",new Object[] {setVslVoyForm.getVslcd()}));
			this.addErrors(request, errors);
			return mapping.getInputForward();
		}else{
			if(process.setVslVoyByBlnumber(blnumber, 
					                       setVslVoyForm.getVslcd(), 
					                       setVslVoyForm.getVoyid(), 
					                       this.getUser(request))==0){
				errors.add("setVslVoyError", new ActionMessage("error.setvslvoy.noblnumber",new Object[] {blnumber}));
				this.addErrors(request, errors);
				return mapping.getInputForward();
				
			}else{
				messages.add("setVslVoyMSG",new ActionMessage("message.success.displayname"));
			}
		}
		//return this.errorHandle(mapping, request, "error.object.notfound", new Object[] {getMessage(request, "booking.displayname"),blnumber});
		//errors.add(error, new ActionMessage(message, objects));
		//this.addErrors(request, errors);
		this.saveMessages(request, messages);
		return mapping.findForward(success);
	}
}