/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.ActionMessages;

import com.apl.sha.ers.model.Vessel;
import com.apl.sha.ers.struts.form.SetVesselForm;
import com.apl.sha.ers.util.BeanUtil;

/** 
 * MyEclipse Struts
 * Creation date: 07-17-2007
 * 
 * XDoclet definition:
 * @struts.action validate="true"
 * @struts.action-forward name="success" path="booking.jsp"
 */
public class SetVesselAction extends BaseAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		if(isCancelled(request)) {
			return cancelHandle(mapping,request,null);
		}
		ActionForward actionForward=this.checkPriv(mapping, request, this.getClass().getSimpleName());
		if(actionForward!=null) return actionForward ;
		SetVesselForm svForm=(SetVesselForm) form;
		Vessel vessel=new Vessel();
		BeanUtil.copyProperties(svForm, vessel);
		process.setVessel(vessel, this.getUser(request));
		request.getSession().getServletContext().setAttribute("vessels", process.getVessels());
		ActionMessages messages=new ActionMessages();
		messages.add("setVesselMSG",new ActionMessage("message.success.displayname"));
		this.saveMessages(request, messages);
		return mapping.findForward(success);
	}
}