/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.form;

import java.util.Date;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-20-2007
 * 
 * XDoclet definition:
 * @struts.form name="adminBulletinForm"
 */
public class getPendingCtnForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** id property */
	private String begPassedDate;
	private String endPassedDate;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = super.validate(mapping, request);
		return errors;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	public String getBegPassedDate() {
		return begPassedDate;
	}

	public void setBegPassedDate(String begPassedDate) {
		this.begPassedDate = begPassedDate;
	}

	public String getEndPassedDate() {
		return endPassedDate;
	}

	public void setEndPassedDate(String endPassedDate) {
		this.endPassedDate = endPassedDate;
	}
	
	
}