/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/**
 * MyEclipse Struts Creation date: 01-24-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="setUserForm"
 */
public class setIvoyEvoyMapForm extends ValidatorForm {
	/*
	 * Generated fields
	 */
	private int v_id;
	private String vslcd;
	private String internal_voyid;
	private String external_voyid;
	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = super.validate(mapping, request);
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	public int getV_id() {
		return v_id;
	}
	public void setV_id(int v_id) {
		this.v_id = v_id;
	}
	public String getVslcd() {
		return vslcd;
	}
	public void setVslcd(String vslcd) {
		this.vslcd = vslcd;
	}
	public String getInternal_voyid() {
		return internal_voyid;
	}
	public void setInternal_voyid(String internal_voyid) {
		this.internal_voyid = internal_voyid;
	}
	public String getExternal_voyid() {
		return external_voyid;
	}
	public void setExternal_voyid(String external_voyid) {
		this.external_voyid = external_voyid;
	}
	
}