/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/**
 * MyEclipse Struts Creation date: 01-24-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="setUserForm"
 */
public class setSVCNameMapForm extends ValidatorForm {
	/*
	 * Generated fields
	 */
	private String svcname;
	private String portofloadingcode;
	private String placeofreturn;
	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = super.validate(mapping, request);
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	public String getSvcname() {
		return svcname;
	}
	public void setSvcname(String svcname) {
		this.svcname = svcname;
	}
	public String getPortofloadingcode() {
		return portofloadingcode;
	}
	public void setPortofloadingcode(String portofloadingcode) {
		this.portofloadingcode = portofloadingcode;
	}
	public String getPlaceofreturn() {
		return placeofreturn;
	}
	public void setPlaceofreturn(String placeofreturn) {
		this.placeofreturn = placeofreturn;
	}
	
}