/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.validator.ValidatorForm;

/**
 * MyEclipse Struts Creation date: 01-24-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="setUserForm"
 */
public class SetUserForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	private int userid;

	private String firstname;

	private String lastname;

	private String username;

	private String oldpwd;

	private String pwd;

	private String cfmpwd;

	private String title;

	private int usergroup;

	private String email;

	private int issys;

	private int status;

	private String privs;

	private String locale;

	private String location;

	private String bookingParty;

	private String depot;

	private String createtime;

	private String updatetime;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = super.validate(mapping, request);
		// check password complexity(char repetition <=3)
		char[] b = pwd.toCharArray();
		int repeat = 0;
		for (int i = 0; i < b.length; i++) {
			int j = i;
			while ((j = pwd.indexOf(b[i], j + 1)) != -1) {
				repeat++;
			}
			if (repeat > 3) {
				errors.add("pwd", new ActionMessage(
						"error.user.password.pattern"));
				break;
			}
			repeat = 0;
		}
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public int getIssys() {
		return issys;
	}

	public void setIssys(int issys) {
		this.issys = issys;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getLocale() {
		return locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getPrivs() {
		return privs;
	}

	public void setPrivs(String privs) {
		this.privs = privs;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public int getUsergroup() {
		return usergroup;
	}

	public void setUsergroup(int usergroup) {
		this.usergroup = usergroup;
	}

	public int getUserid() {
		return userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getCfmpwd() {
		return cfmpwd;
	}

	public void setCfmpwd(String cfmpwd) {
		this.cfmpwd = cfmpwd;
	}

	public String getOldpwd() {
		return oldpwd;
	}

	public void setOldpwd(String oldpwd) {
		this.oldpwd = oldpwd;
	}

	public String getBookingParty() {
		return bookingParty;
	}

	public void setBookingParty(String bookingparty) {
		this.bookingParty = bookingparty;
	}

	public String getDepot() {
		return depot;
	}

	public void setDepot(String depot) {
		this.depot = depot;
	}

	public String getCreatetime() {
		return createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getUpdatetime() {
		return updatetime;
	}

	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

}