/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.apl.sha.ers.struts.form;

import javax.servlet.http.HttpServletRequest;

import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/**
 * MyEclipse Struts Creation date: 01-24-2007
 * 
 * XDoclet definition:
 * 
 * @struts.form name="setUserForm"
 */
public class SetVslVoyForm extends ValidatorForm {
	/*
	 * Generated fields
	 */
	private String vblnumber;
	private String vslcd;
	private String voyid;
	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		ActionErrors errors = super.validate(mapping, request);
		return errors;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
	}

	public String getVblnumber() {
		return vblnumber;
	}

	public void setVblnumber(String vblnumber) {
		this.vblnumber = vblnumber;
	}

	public String getVslcd() {
		return vslcd;
	}

	public void setVslcd(String vslcd) {
		this.vslcd = vslcd.toUpperCase();
	}

	public String getVoyid() {
		return voyid;
	}

	public void setVoyid(String voyid) {
		this.voyid = voyid;
	}
	
}