package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class emailInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../css/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/themes/icon.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.min.js?aa=bb\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/accordion-header.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("#sub, #back {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\tbackground: #307EB7;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tmargin-right: 3px;\r\n");
      out.write("\tmargin-left: 3px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<title>EmailList</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div region=\"center\" style=\"padding: 10px\">\r\n");
      out.write("\t\t<div id=\"acc\" class=\"easyui-accordion\"\r\n");
      out.write("\t\t\tdata-options=\"multiple:true,border:false\" style=\"width: 99%\">\r\n");
      out.write("\t\t\t<div id=\"search\"\r\n");
      out.write("\t\t\t\tdata-options=\"tools:'#seachbutton',collapsible:false\"\r\n");
      out.write("\t\t\t\ttitle=\"<span class='accstyle'><span></span>Search</span>\">\r\n");
      out.write("\t\t\t\t<table id=\"searchtable\" style=\"width: 100%\" cellpadding=\"10\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>ADDRESS:</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"inputtext\" name=\"address\" id=\"address\" /></td>\r\n");
      out.write("\t\t\t\t\t\t<td>TYPE:</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"easyui-combobox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"height:32,width:360\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"type\" name=\"type\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">ALL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Confirmation\">CONFIRMATION</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Amend\">AMEND</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Pending\">PENDING</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"error\">ERROR</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"NewBooking\">NEWBOOKING</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>STATUS:</td>\r\n");
      out.write("\t\t\t\t\t\t<td><select class=\"easyui-combobox\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-options=\"height:32,width:$('#status').parent().width()\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"status\" name=\"status\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\">ALL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"wait\">WAIT</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"sent\">SENT</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"error\">ERROR</option>\r\n");
      out.write("\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t<td>DATE:</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"easyui-datebox\" name=\"startdate\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"startdate\" style=\"height: 32px; width: 180px\" /> --- <input\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"easyui-datebox\" name=\"stoptime\" id=\"stopdate\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"height: 32px; width: 180px\" /></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"list\" data-options=\"tools:'#action',collapsible:false\"\r\n");
      out.write("\t\t\t\ttitle=\"<span class='accstyle'><span></span>Search Results</span>\">\r\n");
      out.write("\t\t\t\t<p><span id='Statistics' style=\"color:red;font-size:15px\"></span></p>\r\n");
      out.write("\t\t\t\t<table id=\"emailList\" name=\"emailList\">\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"seachbutton\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton button\" onclick=\"searchs()\"\r\n");
      out.write("\t\t\tstyle=\"width: 85px; height: 30px; line-height: 30px; color: #000000;\">Search</a>\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton button\" onclick=\"clearsearchs()\"\r\n");
      out.write("\t\t\tstyle=\"width: 125px; height: 30px; line-height: 30px; color: #000000;\">Clear\r\n");
      out.write("\t\t\tSearch</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"mEditdiv\" name=\"mEditdiv\" title=\"Edit Email\" style=\"background: #F5F5F5;\">\r\n");
      out.write("\t\t<div class=\"easyui-layout\" data-options=\"border:false\"\r\n");
      out.write("\t\t\tstyle=\"height: 140px\">\r\n");
      out.write("\t\t\t<form\r\n");
      out.write("\t\t\t\tmethod=\"post\" id=\"form1\" name=\"form1\">\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'center',border:false\"\r\n");
      out.write("\t\t\t\t\tstyle=\"padding-top: 20px; padding-left: 10px;\">\r\n");
      out.write("\t\t\t\t\tAddress: <input id=\"editaddress\" name=\"editaddress\" class=\"inputtext\" />\r\n");
      out.write("\t\t\t\t\t <input type=\"hidden\" id=\"emailid\" name=\"emailid\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'south',border:false\"\r\n");
      out.write("\t\t\t\t\tstyle=\"text-align: center; padding: 12px 0px 0 0; height: 68px; border-top: solid 1px #E9E9E9\">\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0)\" id=\"sub\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"size:'large'\" onclick=\"commit()\"><span\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 18px\">Commit</span></a> <a href=\"javascript:void(0)\"\r\n");
      out.write("\t\t\t\t\t\tid=\"back\" class=\"easyui-linkbutton\" data-options=\"size:'large'\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"returns()\"><span style=\"font-size: 18px\">Return</span></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"action\" name=\"action\" value=\"edit\" />\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"mm1\" style=\"width: 230px;\">\r\n");
      out.write("\t\t<div id=\"mm1-item\" onclick=\"resend()\">Resend</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"selectedIdList\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"action\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"easyui-menubutton\"\r\n");
      out.write("\t\t\tdata-options=\"menu:'#mm1',plain:false,menuAlign:'right'\"\r\n");
      out.write("\t\t\tstyle=\"padding: 10px; width: 105px; height: 30px; line-height: 30px; color: #307EB7; background: -webkit-linear-gradient(white, silver);\"><span\r\n");
      out.write("\t\t\tclass='actionstyle'>Action</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"mPreviewdiv\" name=\"mPreviewdiv\" title=\"Preview Email\" style=\"background: #F5F5F5;\">\r\n");
      out.write("\t\t<div id=\"preview\" name=\"preview\" style=\"padding: 5px;max-height:660px;\" >\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar isfirst = true;//记录是否是首次进入页面\r\n");
      out.write("\t\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("  \t\tvar date = formatDate(new Date());//默认的时间区间为今天\r\n");
      out.write("  \t\t$(\"#startdate\").datebox('setValue' , date);\r\n");
      out.write("  \t\t$(\"#stopdate\").datebox('setValue' , date);\r\n");
      out.write("\t\tloadGrid(\"all\", \"\", \"all\", date, date);\r\n");
      out.write("\t\taccordion_header();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/* 用于修改收件人地址，现暂时关闭 */\r\n");
      out.write("\t$(\"#mEditdiv\").dialog({\r\n");
      out.write("\t\twidth: 360,\r\n");
      out.write("\t\tclosed: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tborder: false,\r\n");
      out.write("\t\tclosable:true,\r\n");
      out.write("\t\tdraggable:false,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\tshadow:false,\r\n");
      out.write("\t\tonClose:function(){\r\n");
      out.write("\t\t\t$(\"#editaddress\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#emailid\").val(\"\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 预览邮件内容 */\r\n");
      out.write("\t$(\"#mPreviewdiv\").dialog({\r\n");
      out.write("\t\twidth: 860,\r\n");
      out.write("\t\tclosed: true,\r\n");
      out.write("\t\tmodal: true,\r\n");
      out.write("\t\tborder: false,\r\n");
      out.write("\t\tclosable:true,\r\n");
      out.write("\t\tdraggable:false,\r\n");
      out.write("\t\tresizable:false,\r\n");
      out.write("\t\tshadow:false,\r\n");
      out.write("\t\tonClose:function(){\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#form1\").form({\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/Email.do\",\r\n");
      out.write("\t    onSubmit: function(){\r\n");
      out.write("\t    \t \r\n");
      out.write("\t    },\r\n");
      out.write("\t    success:function(data){\r\n");
      out.write("\t    \t$(\"#emailList\").datagrid(\"unselectAll\");\r\n");
      out.write("\t    \t$(\"#emailList\").datagrid(\"uncheckAll\");\r\n");
      out.write("\t    \t$(\"#emailList\").datagrid(\"reload\");\r\n");
      out.write("\t    \t$(\"#mEditdiv\").dialog(\"close\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 筛选操作 */\r\n");
      out.write("\tfunction searchs() {\r\n");
      out.write("\t\tvar type = $(\"#type\").combobox(\"getValue\");//邮件类型\r\n");
      out.write("\t\tvar address = $(\"#address\").val();//收件地址\r\n");
      out.write("\t\tvar status = $(\"#status\").combobox(\"getValue\");//邮件发送状态\r\n");
      out.write("\t\tvar startdate = $(\"#startdate\").datebox(\"getValue\");//开始时间\r\n");
      out.write("\t\tvar stopdate = $(\"#stopdate\").datebox(\"getValue\");//结束时间\r\n");
      out.write("\t\tloadGrid(type, address, status, startdate, stopdate);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t/* 清空筛选操作 */\r\n");
      out.write("\tfunction clearsearchs() {\r\n");
      out.write("\t\t$(\"#type\").combobox(\"setValue\",\"all\");\r\n");
      out.write("\t\t$(\"#address\").val(\"\");\r\n");
      out.write("\t\t$(\"#status\").combobox(\"setValue\",\"all\");\r\n");
      out.write("\t\t$(\"#startdate\").datebox(\"setValue\", \"\");\r\n");
      out.write("\t\t$(\"#stopdate\").datebox(\"setValue\", \"\");\r\n");
      out.write("\t\tloadGrid(\"all\", \"\", \"all\", \"\", \"\");\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction loadGrid(type, address, status, startdate, stopdate) {\r\n");
      out.write("\t\t$(\"#emailList\").datagrid({\r\n");
      out.write("\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/Email.do\",\r\n");
      out.write("\t\t\tmethod:\"GET\",\r\n");
      out.write("\t\t\tqueryParams : {\r\n");
      out.write("\t\t\t\t//\"action\" : \"getlist\",\r\n");
      out.write("\t\t\t\t\"type\" : type,\r\n");
      out.write("\t\t\t\t\"address\" : address,\r\n");
      out.write("\t\t\t\t\"status\" : status,\r\n");
      out.write("\t\t\t\t\"startdate\" : startdate,\r\n");
      out.write("\t\t\t\t\"stopdate\" : stopdate\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\twidth : '100%',\r\n");
      out.write("\t\t\tnowrap : false,\r\n");
      out.write("\t\t\tshowFooter : true,\r\n");
      out.write("\t\t\tstriped : true, //隔行变色\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\tpageNumber : 1,\r\n");
      out.write("\t\t\tidField : 'ID',\r\n");
      out.write("\t\t\trownumbers : false,\r\n");
      out.write("\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\tscrollbarSize : 0,\r\n");
      out.write("\t\t\tsingleSelect: false,\r\n");
      out.write("\t\t\trowStyler: function(index,row){\r\n");
      out.write("                 if (row.STATUS == \"error\"){\r\n");
      out.write("                     return 'color:#FF0000;';\r\n");
      out.write("                 }\r\n");
      out.write("            },\r\n");
      out.write("\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\tfield : 'ID',\r\n");
      out.write("\t\t\t\ttitle : 'ID',\r\n");
      out.write("\t\t\t\tcheckbox:true\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'ADDRESS',\r\n");
      out.write("\t\t\t\ttitle : 'ADDRESS',\r\n");
      out.write("\t\t\t\twidth : 160\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'TITLE',\r\n");
      out.write("\t\t\t\ttitle : 'TITLE',\r\n");
      out.write("\t\t\t\twidth : 140\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'STATUS',\r\n");
      out.write("\t\t\t\ttitle : 'STATUS',\r\n");
      out.write("\t\t\t\twidth : 60,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(\"error\" == val){\r\n");
      out.write("\t\t\t\t\t\treturn val + \" (\" + row.SENDINFO + \") \";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn val;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'MAIL_TYPE',\r\n");
      out.write("\t\t\t\ttitle : 'TYPE',\r\n");
      out.write("\t\t\t\twidth : 60\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'CREATEDATE',\r\n");
      out.write("\t\t\t\ttitle : 'CREATEDATE',\r\n");
      out.write("\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'OPTION',\r\n");
      out.write("\t\t\t\ttitle : 'ACTION',\r\n");
      out.write("\t\t\t\twidth : 60,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(row.STATUS == \"wait\"){\r\n");
      out.write("\t\t\t\t\t\treturn '<a href=\"javascript:void(0)\" class=\"easyui-linkbutton linkbutton\" data-options=\"iconCls:icon-search\" onclick=previewdialog()>Preview</a>';\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\treturn '<a href=\"javascript:void(0)\" class=\"easyui-linkbutton linkbutton\" data-options=\"iconCls:icon-search\" onclick=previewdialog()>View</a>';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//return '<a href=\"javascript:void(0)\" class=\"easyui-linkbutton linkbutton\" data-options=\"iconCls:icon-search\" onclick=previewdialog()>Preview</a>&nbsp;&nbsp;<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" onclick=opendialog('+row.ID+',\"'+row.ADDRESS+'\")>Edit</a>';\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}]],\r\n");
      out.write("\t\t\tonClickRow : function(rowIndex, rowData) {\r\n");
      out.write("\t\t\t\t$(\"#preview\").html(rowData.CONTENTCLOB);\r\n");
      out.write("\t\t\t\tif(rowData.MAIL_TYPE==\"Amend\"){\r\n");
      out.write("\t\t\t\t\t$(\"#mPreviewdiv\").dialog(\"resize\",{width: 860,height:500});\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#mPreviewdiv\").dialog(\"resize\",{width: 310,height:300});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#mPreviewdiv\").dialog(\"center\");\r\n");
      out.write("\t\t\t\t$(\"#emailList\").datagrid(\"unselectRow\",rowIndex);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonLoadSuccess : function() {\r\n");
      out.write("\t\t\t\tvar Statistics = $(this).datagrid(\"getData\").Statistics;//统计邮件发送信息\r\n");
      out.write("\t\t\t\tvar send=0;\r\n");
      out.write("\t\t\t\tvar error=0;\r\n");
      out.write("\t\t\t\tvar wait=0;\r\n");
      out.write("\t\t\t\tfor( i=0; i<Statistics.length; i++){\r\n");
      out.write("\t\t\t\t\tif(Statistics[i].STATUS == \"error\"){//发送失败数\r\n");
      out.write("\t\t\t\t\t\terror = Statistics[i].COUNT;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(Statistics[i].STATUS == \"sent\"){//发送成功数\r\n");
      out.write("\t\t\t\t\t\tsend = Statistics[i].COUNT;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(Statistics[i].STATUS == \"wait\"){//等待发送数\r\n");
      out.write("\t\t\t\t\t\twait = Statistics[i].COUNT;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$(\"#Statistics\").html(\"WaitQty&nbsp;:&nbsp;&nbsp;\"+wait+\"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SentQty&nbsp;:&nbsp;&nbsp;\"+send+\"&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;ErrQty&nbsp;:&nbsp;&nbsp;\"+error);\r\n");
      out.write("\t\t\t\t$(\"#acc\").accordion(\"select\", 1);\r\n");
      out.write("\t\t\t\tif(isfirst){\r\n");
      out.write("\t\t\t\t\tisfirst=false;\r\n");
      out.write("\t\t\t\t\tstatusRefresh();//定时刷新发送状态\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction opendialog(id,address){\r\n");
      out.write("\t\t$(\"#emailid\").val(id);\r\n");
      out.write("\t\t$(\"#editaddress\").val(address);\r\n");
      out.write("\t\t$(\"#mEditdiv\").dialog(\"open\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction previewdialog(){\r\n");
      out.write("\t\t$(\"#mPreviewdiv\").dialog(\"open\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction commit(){\r\n");
      out.write("\t\t $(\"#form1\").submit();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction returns(){\r\n");
      out.write("\t\t$(\"#mEditdiv\").dialog(\"close\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 邮件批量重新发送 */\r\n");
      out.write("\tfunction resend(){\r\n");
      out.write("\t\tvar emailidList = $(\"#emailList\").datagrid(\"getSelections\");\r\n");
      out.write("\t\tif (emailidList != null && emailidList !=\"\") {\r\n");
      out.write("\t\t\tvar ids = \"\";\r\n");
      out.write("\t\t\tfor(var i = 0; i < emailidList.length; i++){\r\n");
      out.write("\t\t\t\tids += emailidList[i].ID + \",\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(ids != \"\"){\r\n");
      out.write("\t\t\t\tids = ids.substring(0 , ids.length - 1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/Email.do\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\tdata:{ \"ids\" : ids },\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t    \t$(\"#emailList\").datagrid(\"unselectAll\");\r\n");
      out.write("\t\t\t    \t$(\"#emailList\").datagrid(\"uncheckAll\");\r\n");
      out.write("\t\t\t\t\t$('#emailList').datagrid(\"reload\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 邮件状态定时刷新 */\r\n");
      out.write("\tfunction statusRefresh() {\r\n");
      out.write("\t\tvar emailidList = $(\"#emailList\").datagrid(\"getRows\");\r\n");
      out.write("\t\tvar type = $(\"#type\").combobox(\"getValue\");\r\n");
      out.write("\t\tvar address = $(\"#address\").val();\r\n");
      out.write("\t\tvar status = $(\"#status\").combobox(\"getValue\");\r\n");
      out.write("\t\tvar startdate = $(\"#startdate\").datebox(\"getValue\");\r\n");
      out.write("\t\tvar stopdate = $(\"#stopdate\").datebox(\"getValue\");\r\n");
      out.write("\t\tif (emailidList != null && emailidList !=\"\") {\r\n");
      out.write("\t\t\tvar ids = \"\";\r\n");
      out.write("\t\t\tfor(var i = 0; i < emailidList.length; i++){\r\n");
      out.write("\t\t\t\tids += emailidList[i].ID + \",\";\r\n");
      out.write("\t\t\t\t//ids += \"&IDS=\" + emailidList[i].ID;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(ids != \"\"){\r\n");
      out.write("\t\t\t\tids = ids.substring(0 , ids.length - 1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"");
      out.print(request.getContextPath());
      out.write("/EmailStatus.do\",\r\n");
      out.write("\t\t\t\tmethod : \"post\",\r\n");
      out.write("\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t//data:\"Content-type=application/x-www-form-urlencoded&type=\"+type+\"&address=\"+address+\"&status=\"+status+\"&startdate=\"+startdate+\"&stopdate=\"+stopdate+\"&action=refreshstatus\"+ids,\r\n");
      out.write("\t\t\t\tdata:{\"type\" : type , \"address\" : address , \"status\" : status , \"startdate\" : startdate , \"stopdate\" : stopdate , \"ids\" : ids},\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tvar Statistics = data.Statistics;\r\n");
      out.write("\t\t\t\t\tvar send=0;\r\n");
      out.write("\t\t\t\t\tvar error=0;\r\n");
      out.write("\t\t\t\t\tvar wait=0;\r\n");
      out.write("\t\t\t\t\tfor( i=0; i<Statistics.length; i++){\r\n");
      out.write("\t\t\t\t\t\tif(Statistics[i].STATUS == \"error\"){\r\n");
      out.write("\t\t\t\t\t\t\terror = Statistics[i].COUNT;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(Statistics[i].STATUS == \"sent\"){\r\n");
      out.write("\t\t\t\t\t\t\tsend = Statistics[i].COUNT;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(Statistics[i].STATUS == \"wait\"){\r\n");
      out.write("\t\t\t\t\t\t\twait = Statistics[i].COUNT;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#Statistics\").html(\"WaitQty&nbsp;:&nbsp;&nbsp;\"+wait+\"&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;SendQty&nbsp;:&nbsp;&nbsp;\"+send+\"&nbsp;&nbsp&nbsp;&nbsp;&nbsp;&nbsp;ErrQty&nbsp;:&nbsp;&nbsp;\"+error);\r\n");
      out.write("\t\t\t\t\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t\t\t\t\t$('#emailList').datagrid('updateRow',{\r\n");
      out.write("\t\t\t\t\t\t\tindex: i,\r\n");
      out.write("\t\t\t\t\t\t\trow: {\r\n");
      out.write("\t\t\t\t\t\t\t\tSTATUS: data.rows[i].STATUS\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tsetTimeout(\"statusRefresh()\",10000);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 格式化日期 */\r\n");
      out.write("\tfunction formatDate(date){\r\n");
      out.write("\t\tvar day = date.getDate() > 9 ? date.getDate() : \"0\" + date.getDate();\r\n");
      out.write("\t\tvar month = (date.getMonth() + 1) > 9 ? (date.getMonth() + 1) : \"0\" + (date.getMonth() + 1);\r\n");
      out.write("\t\treturn date.getFullYear() + '-' + month + '-' + day;\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
