package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rangeInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../css/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/themes/icon.css\">\r\n");
      out.write("<style>\r\n");
      out.write("#sub, #back {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\tbackground: #307EB7;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tmargin-right: 3px;\r\n");
      out.write("\tmargin-left: 3px;\r\n");
      out.write("}\r\n");
      out.write(".bold{\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("}\r\n");
      out.write("#edittable{\r\n");
      out.write("\tborder-left: 2px solid #666; \r\n");
      out.write("\tborder-bottom: 2px solid #666;\r\n");
      out.write("}\r\n");
      out.write("#edittable th{\r\n");
      out.write("\tfont-weight:bold;\r\n");
      out.write("\tbackground-color:#D3D3D3;\r\n");
      out.write("}\r\n");
      out.write("#edittable td,#edittable th{\r\n");
      out.write("   border-right:2px solid #666;\r\n");
      out.write("   border-top: 2px solid #666;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.min.js?aa=bb\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/accordion-header.js\"></script>\r\n");
      out.write("<title>Range Manage</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div region=\"center\" style=\"padding: 10px;\">\r\n");
      out.write("\t\t<div id=\"acc\" class=\"easyui-accordion\"\r\n");
      out.write("\t\t\tdata-options=\"multiple:true,border:false\" style=\"width: 99%\">\r\n");
      out.write("\t\t\t<div id=\"search\"\r\n");
      out.write("\t\t\t\tdata-options=\"tools:'#seachbutton',collapsible:false\"\r\n");
      out.write("\t\t\t\ttitle=\"<span class='accstyle'><span></span>Search</span>\">\r\n");
      out.write("\t\t\t\t<table id=\"searchtable\"  cellpadding=\"10\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>Name:</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input class=\"inputtext\" name=\"searchcode\" id=\"searchcode\" style=\"width:180px\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Booking# Log:</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"easyui-combobox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"height:32,width:180\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"type\" name=\"type\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"all\">ALL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"Active\">Active</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Editable:</td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"easyui-combobox\"\r\n");
      out.write("\t\t\t\t\t\t\t\tdata-options=\"height:32,width:180\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"editable\" name=\"editable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"all\">ALL</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"edit\">Edit</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"list\" data-options=\"collapsible:false,tools:'#menu'\"\r\n");
      out.write("\t\t\t\ttitle=\"<span class='accstyle'><span></span>List</span>\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"ManageList\" name=\"ManageList\">\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-menubutton\" data-options=\"menu:'#mm1',plain:false,menuAlign:'right'\" style=\"padding:10px;width:105px;height:30px;line-height:30px;color:#307EB7;background:-webkit-linear-gradient(white,silver);filter:none;\"><span class='actionstyle'>Query</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"mm1\" style=\"width:230px;\">\r\n");
      out.write("\t \t<!-- <div onclick='loadgrid(2,\"\",\"valid\")'>Country</div>  -->\r\n");
      out.write("        <div onclick='loadgrid(3,\"\",\"Active\",\"edit\")'>Location</div>\r\n");
      out.write("        <div onclick='loadgrid(4,\"\",\"Active\",\"edit\")'>Booking Party</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\t<div id=\"seachbutton\">\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton button\" onclick=\"searchs()\"\r\n");
      out.write("\t\t\tstyle=\"width: 85px; height: 30px; line-height: 30px; color: #000000;\">Search</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton button\" onclick=\"clearsearchs()\"\r\n");
      out.write("\t\t\tstyle=\"width: 125px; height: 30px; line-height: 30px; color: #000000;\">Clear\r\n");
      out.write("\t\t\tSearch</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar curlevel=\"3\";//页面初始化等级为location，默认查出location数据\r\n");
      out.write("\tvar local = \"");
      out.print( request.getSession().getAttribute("local") );
      out.write("\";//获取当前用户地区\r\n");
      out.write("\tvar userid = \"");
      out.print( request.getSession().getAttribute("userid") );
      out.write("\";//获取当前用户id\r\n");
      out.write("\tvar groupid = \"");
      out.print( request.getSession().getAttribute("groupid") );
      out.write("\";//获取当前用户分组id\r\n");
      out.write("\t\r\n");
      out.write("\t/* 页面加载完毕后进入操作 */\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\twindow.top.updatetitle(\"Maintaintitles\",\"Bkg# Range\");//修改蓝色部分标题显示文字\r\n");
      out.write("\t\tloadgrid(curlevel,\"\",\"Active\",\"edit\");//加载树状表格，默认为Location等级的树状表格，子节点默认仅显示有效\r\n");
      out.write("\t\t$(\"#type\").combobox(\"setValue\",\"Active\");//设置Booking# Log的选项为Active，默认查正在使用中的数据\r\n");
      out.write("\t\t$(\"#editable\").combobox(\"setValue\",\"edit\");\r\n");
      out.write("\t\taccordion_header();//初始化折叠菜单\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 表格筛选操作 */\r\n");
      out.write("  \tfunction searchs(){\r\n");
      out.write("  \t\tvar searchcode = $(\"#searchcode\").val();//获取Name的值\r\n");
      out.write("  \t\tvar searchtype = $(\"#type\").combobox(\"getValue\");//获取Booking# Log的值\r\n");
      out.write("  \t\tvar editable = $(\"#editable\").combobox(\"getValue\");//是否只显示可编辑的\r\n");
      out.write("  \t\tloadgrid(curlevel,searchcode,searchtype,editable);//根据等级、Name、Booking# Log筛选数据\r\n");
      out.write("  \t}\r\n");
      out.write("  \t\r\n");
      out.write("\t/* 重置条件操作 */\r\n");
      out.write("  \tfunction clearsearchs(){\r\n");
      out.write("  \t\t$(\"#searchcode\").val(\"\");\r\n");
      out.write("  \t\t$(\"#editable\").combobox(\"setValue\",\"edit\");\r\n");
      out.write("  \t\t$(\"#type\").combobox(\"setValue\",\"Active\");\r\n");
      out.write("  \t\tloadgrid(curlevel,\"\",\"Active\");\r\n");
      out.write("  \t}\r\n");
      out.write("  \t\r\n");
      out.write("\t/* 加载树状表格 leval:查询范围等级(Location、Booking Party) code:名称或编号  type:是否删除 */\r\n");
      out.write("\tfunction loadgrid(leval,code,type,editable){\r\n");
      out.write("\t\tcurlevel=leval;\r\n");
      out.write("\t\t$(\"#ManageList\").treegrid({\r\n");
      out.write("\t\t\turl:'");
      out.print(request.getContextPath());
      out.write("/Range.do', //进入后台url\r\n");
      out.write("\t\t\tqueryParams : {//传到后台的参数集合\r\n");
      out.write("\t\t\t\t\"action\" : \"loadlist\",//操作为加载列表\r\n");
      out.write("\t\t\t\t\"level\":leval,//等级\r\n");
      out.write("\t\t\t\t\"code\":code,//编号\r\n");
      out.write("\t\t\t\t\"type\":type,//是否有效\r\n");
      out.write("\t\t\t\t\"editable\":editable\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\twidth : '100%',\r\n");
      out.write("\t\t\tmethod: 'post',\r\n");
      out.write("\t\t\tnowrap : false,\r\n");
      out.write("\t\t\tshowFooter : true,\r\n");
      out.write("\t\t\tstriped : true, //隔行变色\r\n");
      out.write("\t\t\tpagination : true,//是否分页\r\n");
      out.write("\t\t\tpageSize : 10,//每页默认显示行数\r\n");
      out.write("\t\t\tpageNumber : 1,//默认起始页数\r\n");
      out.write("\t\t\tidField : 'ID',//主键filed\r\n");
      out.write("\t\t\trownumbers : false,//是否显示编号\r\n");
      out.write("\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\tscrollbarSize : 0,\r\n");
      out.write("\t\t\ttreeField:\"CODE\",//作为树节点的filed\r\n");
      out.write("\t\t\t/* 表格列属性设置 */\r\n");
      out.write("\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\tfield : 'CODE',//显示后台数据中code的值\r\n");
      out.write("\t\t\t\ttitle : 'NAME',//前台显示列的标题\r\n");
      out.write("\t\t\t\twidth : 190,formatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(val == 'default'){//将小写default的转为大写显示\r\n");
      out.write("\t\t\t\t\t\tval = 'DEFAULT';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.DESC_CN!=null){//判断是否有中文显示，有则显示\r\n");
      out.write("\t\t\t\t\t\treturn row.DESC_CN + \"(\" + val + \")\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn val;\r\n");
      out.write("\t\t\t\t},styler:function(value,row,index){\r\n");
      out.write("\t\t\t\t\tif(row.ISDELETE==1){//无效的范围文字显示为红色\r\n");
      out.write("\t\t\t\t\t\treturn \"color:#FF0000;font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL!=curlevel){//子节点的文字显示为10px\r\n");
      out.write("\t\t\t\t\t\treturn \"font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'NO_WAVE1_MIN',//显示WBP的最小值和最大值\r\n");
      out.write("\t\t\t\ttitle : 'WBP',\r\n");
      out.write("\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL==curlevel){//判断是否是父节点内容\r\n");
      out.write("\t\t\t\t\t\treturn val+\"--\"+row.NO_WAVE1_MAX;//显示格式为”最小值--最大值“\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn '&nbsp;&nbsp;&nbsp;&nbsp;'+val+\"--\"+row.NO_WAVE1_MAX;//显示格式为”最小值--最大值“,并进行缩进\r\n");
      out.write("\t\t\t\t},styler:function(value,row,index){\r\n");
      out.write("\t\t\t\t\tif(row.ISDELETE==1){//无效的范围文字显示为红色\r\n");
      out.write("\t\t\t\t\t\treturn \"color:#FF0000;font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL!=curlevel){//子节点的文字显示为10px\r\n");
      out.write("\t\t\t\t\t\treturn \"font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'NO_WAVE1_LAST_USED_ID',//显示WBP的当前使用的值\r\n");
      out.write("\t\t\t\ttitle : 'WBP_LAST',\r\n");
      out.write("\t\t\t\twidth : 80,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(row.ISDELETE==1){//无效的不显示\r\n");
      out.write("\t\t\t\t\t\treturn \"\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL==curlevel){//判断是否是父节点内容\r\n");
      out.write("\t\t\t\t\t\treturn val;//正常显示\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn '&nbsp;&nbsp;&nbsp;&nbsp;'+val;//对显示进行缩进\r\n");
      out.write("\t\t\t\t},styler:function(value,row,index){\r\n");
      out.write("\t\t\t\t\tif(row.ISDELETE==1){//无效的范围文字显示为红色\r\n");
      out.write("\t\t\t\t\t\treturn \"color:#FF0000;font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL!=curlevel){//子节点的文字显示为10px\r\n");
      out.write("\t\t\t\t\t\treturn \"font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'WAVE1_MIN',//显示CSSS的最小值和最大值\r\n");
      out.write("\t\t\t\ttitle : 'CSSS',\r\n");
      out.write("\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL==curlevel){//判断是否是父节点内容\r\n");
      out.write("\t\t\t\t\t\treturn val+\"--\"+row.WAVE1_MAX;//显示格式为”最小值--最大值“\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn '&nbsp;&nbsp;&nbsp;&nbsp;'+val+\"--\"+row.WAVE1_MAX;//显示格式为”最小值--最大值“,并进行缩进\r\n");
      out.write("\t\t\t\t},styler:function(value,row,index){\r\n");
      out.write("\t\t\t\t\tif(row.ISDELETE==1){//无效的范围文字显示为红色\r\n");
      out.write("\t\t\t\t\t\treturn \"color:#FF0000;font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL!=curlevel){//子节点的文字显示为10px\r\n");
      out.write("\t\t\t\t\t\treturn \"font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'WAVE1_LAST_USED_ID',//显示CSSS的上一次使用的值\r\n");
      out.write("\t\t\t\ttitle : 'CSSS_LAST',\r\n");
      out.write("\t\t\t\twidth : 80,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(row.ISDELETE==1){//无效的不显示\r\n");
      out.write("\t\t\t\t\t\treturn \"\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL==curlevel){//判断是否是父节点内容\r\n");
      out.write("\t\t\t\t\t\treturn val;//正常显示\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn '&nbsp;&nbsp;&nbsp;&nbsp;'+val;//对显示进行缩进\r\n");
      out.write("\t\t\t\t},styler:function(value,row,index){\r\n");
      out.write("\t\t\t\t\tif(row.ISDELETE==1){//无效的范围文字显示为红色\r\n");
      out.write("\t\t\t\t\t\treturn \"color:#FF0000;font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL!=curlevel){//子节点的文字显示为10px\r\n");
      out.write("\t\t\t\t\t\treturn \"font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'OPTION',//显示操作按钮\r\n");
      out.write("\t\t\t\ttitle : 'OPTION',\r\n");
      out.write("\t\t\t\twidth : 50,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(row.APL_OFFICE == local || row.CODE == local){//根据当前用户的等级和地区控制是否显示编辑按钮\r\n");
      out.write("\t\t\t\t\t\tif(row.BK_LEVEL==curlevel){//子节点不显示编辑按钮\r\n");
      out.write("\t\t\t\t\t\t\treturn '<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"size:large\" onclick=defaultlist(\"'+row.ID+'\",\"'+row.CODE+'\",\"'+row.BK_LEVEL+'\",\"'+row.WAVE1_MIN+'\",\"'+row.WAVE1_MAX+'\",\"'+row.NO_WAVE1_MIN+'\",\"'+row.NO_WAVE1_MAX+'\",\"'+row.DESC_CN+'\")>Edit</a>';\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},styler:function(value,row,index){\r\n");
      out.write("\t\t\t\t\tif(row.ISDELETE==1){//无效的范围文字显示为红色\r\n");
      out.write("\t\t\t\t\t\treturn \"color:#FF0000;font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.BK_LEVEL!=curlevel){//子节点的文字显示为10px\r\n");
      out.write("\t\t\t\t\t\treturn \"font-size:10px\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ] ],\r\n");
      out.write("\t\t\t/* 加载成功执行操作 */\r\n");
      out.write("\t\t\tonLoadSuccess : function() {\r\n");
      out.write("\t\t\t\t$(\"#acc\").accordion(\"select\", 1);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 进入编辑页面并传入参数在蓝色标题处显示 */\r\n");
      out.write("\tfunction defaultlist(id,code,level,WAVE1_MIN,WAVE1_MAX,NO_WAVE1_MIN,NO_WAVE1_MAX,DESC_CN){\r\n");
      out.write("\t\tvar name = \"\";\r\n");
      out.write("\t\tif(DESC_CN != null && DESC_CN != 'undefined' && DESC_CN != 'null' ){//判断中文名是否存在，存在则显示中文\r\n");
      out.write("\t\t\tname=DESC_CN;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tname=code;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\twindow.top.updatetitle(\"Maintaintitles\",name +\" | \"+\"WBP Range:&nbsp;&nbsp;&nbsp;&nbsp;\"+NO_WAVE1_MIN+\"--\"+NO_WAVE1_MAX+\"&nbsp;&nbsp;&nbsp;&nbsp;CSSS Range:&nbsp;&nbsp;&nbsp;&nbsp;\"+WAVE1_MIN+\"--\"+WAVE1_MAX);//修改蓝色标题文字，显示出当前编辑的code和范围信息\r\n");
      out.write("\t\tlocation.href=\"rangeEdit.jsp?parentid=\"+id+\"&code=\"+code+\"&level=\"+level+\"&wavemin=\"+WAVE1_MIN+\"&wavemax=\"+WAVE1_MAX+\"&nowavemin=\"+NO_WAVE1_MIN+\"&nowavemax=\"+NO_WAVE1_MAX;//跳转到编辑页面\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
