package org.apache.jsp.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rangeEdit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("\thref=\"../css/themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/themes/icon.css\">\r\n");
      out.write("<style>\r\n");
      out.write("#sub, #back {\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("\tbackground: #307EB7;\r\n");
      out.write("\tcolor: #ffffff;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\tmargin-right: 3px;\r\n");
      out.write("\tmargin-left: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bold {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#edittable {\r\n");
      out.write("\tborder-left: 1px solid #E9E9E9;\r\n");
      out.write("\tborder-bottom: 1px solid #E9E9E9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#edittable th {\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tbackground: #F6F6F6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#edittable td, #edittable th {\r\n");
      out.write("\tborder-right: 1px solid #E9E9E9;\r\n");
      out.write("\tborder-top: 1px solid #E9E9E9;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#acc2 .panel-tool {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tmargin-top: -15px;\r\n");
      out.write("\theight: 32px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#acc2 .panel-icon {\r\n");
      out.write("\tleft: 5px;\r\n");
      out.write("\twidth: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#acc2 .panel-tool {\r\n");
      out.write("\tright: 3px;\r\n");
      out.write("\twidth: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#acc2 .panel-tool a {\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.min.js?aa=bb\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"../js/accordion-header.js\"></script>\r\n");
      out.write("<title>RangeMaintain</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\">\r\n");
      out.write("\t<div region=\"center\" data-options=\"border:false\" style=\"padding: 10px;\">\r\n");
      out.write("\t\t<div id=\"acc\" class=\"easyui-accordion\"\r\n");
      out.write("\t\t\tdata-options=\"multiple:true,border:false\" style=\"width: 98%;\">\r\n");
      out.write("\t\t\t<div id=\"edit\" data-options=\"tools:'#edittool',collapsible:false\"\r\n");
      out.write("\t\t\t\ttitle=\"<span class='accstyle'><span></span>Edit</span>\">\r\n");
      out.write("\t\t\t\t<form id=\"form1\" name=\"form1\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<span id='range' style=\"color: #FF0000\"></span>\r\n");
      out.write("\t\t\t\t\t<table id=\"edittable\" name=\"edittable\" width=\"100%\" border=\"0\"\r\n");
      out.write("\t\t\t\t\t\tcellspacing=\"0\" cellpadding=\"5\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th rowspan=\"2\" style=\"width: 80px\">NAME</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th colspan=\"3\">WBP</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th colspan=\"3\">CSSS</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th rowspan=\"2\" style=\"width: 20px\"></th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>MIN</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>MAX</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>LAST</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>MIN</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>MAX</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>LAST</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody></tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"action\" id=\"action\" /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"level\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(request.getParameter("level"));
      out.write("\"> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"parentid\" id=\"parentid\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(request.getParameter("parentid"));
      out.write("\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"list2\" data-options=\"collapsible:false,tools:'#showall'\"\r\n");
      out.write("\t\t\t\ttitle=\"<span class='accstyle'><span></span>List</span>\"\r\n");
      out.write("\t\t\t\tstyle=\"padding: 0px;\">\r\n");
      out.write("\t\t\t\t<div class=\"easyui-layout\" style=\"height: 300px\">\r\n");
      out.write("\t\t\t\t\t<div data-options=\"region:'center'\" style=\"padding: 0px;\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"defaultlist\" name=\"defaultlist\">\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div data-options=\"region:'south',border:false\"\r\n");
      out.write("\t\tstyle=\"text-align: right; padding: 12px 0px 0 0; height: 68px;\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" id=\"sub\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\tdata-options=\"size:'large'\" onclick=\"sub()\"><span\r\n");
      out.write("\t\t\tstyle=\"font-size: 18px\">Commit</span></a> <a href=\"javascript:void(0)\"\r\n");
      out.write("\t\t\tonclick=\"back()\" id=\"back\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\tdata-options=\"size:'large'\"><span style=\"font-size: 18px\">Return</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"edittool\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr id=\"editlocation\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<td class=\"bold\">Please Select a\r\n");
      out.write("\t\t\t\t\tLocation:&nbsp;&nbsp;&nbsp;&nbsp; <select id=\"location\"\r\n");
      out.write("\t\t\t\t\tname=\"location\" style=\"height: 25px; width: 180px;\"></select>\r\n");
      out.write("\t\t\t\t\t<button onclick=\"addtr('location')\">+</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr id=\"editbp\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<td class=\"bold\" align=right>Please Select a Booking\r\n");
      out.write("\t\t\t\t\tParty:&nbsp;&nbsp;&nbsp;&nbsp; <select id=\"bp\" name=\"bp\"\r\n");
      out.write("\t\t\t\t\tstyle=\"height: 25px; width: 180px\"></select>\r\n");
      out.write("\t\t\t\t\t<button onclick=\"addtr('bp')\">+</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr id=\"editorign\" style=\"display: none\">\r\n");
      out.write("\t\t\t\t<td class=\"bold\" align=right>Please Select a\r\n");
      out.write("\t\t\t\t\torign:&nbsp;&nbsp;&nbsp;&nbsp; <select id=\"orign\" name=\"orign\"\r\n");
      out.write("\t\t\t\t\tstyle=\"height: 25px; width: 180px\"></select>\r\n");
      out.write("\t\t\t\t\t<button onclick=\"addtr('orign')\">+</button>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"showall\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td class=\"bold\"><input type=\"checkbox\" id=\"check\" name=\"check\"\r\n");
      out.write("\t\t\t\t\tonclick=\"changecheck()\" />Show Log</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("\tvar parentid=\"");
      out.print(request.getParameter("parentid"));
      out.write("\";\r\n");
      out.write("\tvar level=\"");
      out.print(request.getParameter("level"));
      out.write("\";\r\n");
      out.write("\tvar code=\"");
      out.print(request.getParameter("code"));
      out.write("\"; \r\n");
      out.write("\tvar wavemax=\"");
      out.print(request.getParameter("wavemax"));
      out.write("\";\r\n");
      out.write("\tvar wavemin=\"");
      out.print(request.getParameter("wavemin"));
      out.write("\";\r\n");
      out.write("\tvar nowavemax=\"");
      out.print(request.getParameter("nowavemax"));
      out.write("\";\r\n");
      out.write("\tvar nowavemin=\"");
      out.print(request.getParameter("nowavemin"));
      out.write("\";\r\n");
      out.write("\t\r\n");
      out.write("\t/* 页面加载完毕后进入操作 */\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\taccordion_header();\r\n");
      out.write("\t\tif(level==2){//Country等级操作，已关闭\r\n");
      out.write("\t  \t\t$(\"#editorign\").css(\"display\",\"none\");\r\n");
      out.write("\t  \t\t$(\"#editbp\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t$(\"#editlocation\").css(\"display\",\"\");\r\n");
      out.write("\t\t\t$(\"#action\").val(\"editlocation\");\r\n");
      out.write("\t\t} else if(level==3) {//Location等级操作\r\n");
      out.write("\t\t\t$('#bp').combobox({//加载booking party的下拉列表,用于添加编辑操作\r\n");
      out.write("\t\t\t\turl:'");
      out.print(request.getContextPath());
      out.write("/BpCombo.do?code=' + code,\r\n");
      out.write("\t\t\t\tmethod:'get',\r\n");
      out.write("\t\t\t\tvalueField:'COMID',\r\n");
      out.write("\t\t\t\ttextField:'TEXT',\r\n");
      out.write("\t\t\t\teditable:true,\r\n");
      out.write("\t\t\t\tonLoadSuccess:function(){\r\n");
      out.write("\t\t\t\t\t$('#bp').combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tonSelect:function(data){\r\n");
      out.write("\t\t\t\t\t//loadGrid(data.ID);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tfilter: function(q, row){//筛选时大小写不敏感\r\n");
      out.write("\t\t\t\t\tvar opts = $(this).combobox('options');\r\n");
      out.write("\t\t\t\t\treturn row[opts.textField].indexOf(q.toUpperCase()) == 0;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t  \t\t$(\"#editorign\").css(\"display\",\"none\");\r\n");
      out.write("\t  \t\t$(\"#editbp\").css(\"display\",\"\");\r\n");
      out.write("\t\t\t$(\"#editlocation\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t$(\"#action\").val(\"editbp\");\r\n");
      out.write("\t\t} else if(level==4) {//Booking Party等级操作\r\n");
      out.write("\t  \t\t$(\"#editorign\").css(\"display\",\"\");\r\n");
      out.write("\t  \t\t$(\"#editbp\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t$(\"#editlocation\").css(\"display\",\"none\");\r\n");
      out.write("\t\t\t$(\"#action\").val(\"editorign\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tqueryList(parentid,level,\"Active\");//加载当前编辑数据下的子节点数据，根据parentid筛选\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t/* 表单提交操作 */\r\n");
      out.write("\t$(\"#form1\").form({\r\n");
      out.write("\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/RangeDetail.do\",\r\n");
      out.write("\t    onSubmit: function(){\r\n");
      out.write("\t    \t return $(this).form('enableValidation').form('validate');\r\n");
      out.write("\t    },\r\n");
      out.write("\t    success:function(data){\r\n");
      out.write("\t    \t$(\"#defaultlist\").datagrid(\"reload\");\r\n");
      out.write("\t    \t$(\"#edittable tbody\").html(\"\");\r\n");
      out.write("\t    \twindow.top.isexitfn(false);\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t/* 加载orign的下拉列表 */\r\n");
      out.write("\t$('#orign').combobox({\r\n");
      out.write("\t\turl:'");
      out.print(request.getContextPath());
      out.write("/OriginCombo.do',\r\n");
      out.write("\t\tmethod:'GET',\r\n");
      out.write("\t\tvalueField:'COMID',\r\n");
      out.write("\t\ttextField:'TEXT',\r\n");
      out.write("\t\teditable:true,\r\n");
      out.write("\t\tonLoadSuccess:function(){\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tonSelect:function(data){\r\n");
      out.write("\t\t\t//loadGrid(data.ID);\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tfilter: function(q, row){//筛选时大小写不敏感\r\n");
      out.write("\t\t\tvar opts = $(this).combobox('options');\r\n");
      out.write("\t\t\treturn row[opts.textField].indexOf(q.toUpperCase()) == 0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("  \t\r\n");
      out.write("\t/* 判断是否显示无效数据 */\r\n");
      out.write("\tfunction changecheck(){\r\n");
      out.write("\t\tif($(\"#check\").is(\":checked\")){\r\n");
      out.write("\t\t\tqueryList(parentid,level,\"all\");\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tqueryList(parentid,level,\"Active\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 加载当前编辑数据下的子节点数据表格 */\r\n");
      out.write("\tfunction queryList(id,level,type){\r\n");
      out.write("\t\t$(\"#parentid\").val(id);\r\n");
      out.write("\t\t$(\"#defaultlist\").datagrid({\r\n");
      out.write("\t\t\turl:'");
      out.print(request.getContextPath());
      out.write("/RangeDetail.do',\r\n");
      out.write("\t\t\tmethod:'GET',\r\n");
      out.write("\t\t\tqueryParams : {\r\n");
      out.write("\t\t\t\t\"parentId\" : parentid,//通过传入父id获取它下面的所有子节点信息\r\n");
      out.write("\t\t\t\t\"type\":type\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ttoolbar:[{//加载编辑按钮\r\n");
      out.write("\t\t\t\t text:'Edit',\r\n");
      out.write("\t\t         iconCls:'icon-edit',\r\n");
      out.write("\t\t         handler:function(){\r\n");
      out.write("\t\t        \t dotoolbar('edit');\r\n");
      out.write("\t\t        \t //alert('Edit');\r\n");
      out.write("\t\t         }\r\n");
      out.write("\t\t\t},{//加载删除按钮\r\n");
      out.write("\t            text:'Remove',\r\n");
      out.write("\t            iconCls:'icon-remove',\r\n");
      out.write("\t            handler:function(){\r\n");
      out.write("\t            \tdotoolbar('remove');\r\n");
      out.write("\t            \t//alert('cut');\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }],\r\n");
      out.write("\t\t\twidth : '100%',\r\n");
      out.write("\t\t\tnowrap : false,\r\n");
      out.write("\t\t\tshowFooter : true,\r\n");
      out.write("\t\t\tstriped : true, //隔行变色\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\tpageNumber : 1,\r\n");
      out.write("\t\t\tidField : 'ID',\r\n");
      out.write("\t\t\trownumbers : false,\r\n");
      out.write("\t\t\tfitColumns : true,\r\n");
      out.write("\t\t\tsingleSelect: false,\r\n");
      out.write("\t\t\tfit:true,\r\n");
      out.write("\t\t\tscrollbarSize : 0,\r\n");
      out.write("\t\t\trowStyler: function(index,row){\r\n");
      out.write("\t\t\t\tif(row.ISDELETE==1){\r\n");
      out.write("                    return 'color:#FF0000;';\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\tfield : 'ID',\r\n");
      out.write("\t\t\t\ttitle : 'ID',\r\n");
      out.write("\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\tcheckbox:true\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'CODE',\r\n");
      out.write("\t\t\t\ttitle : 'NAME',\r\n");
      out.write("\t\t\t\twidth : 100,formatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(val == 'default'){\r\n");
      out.write("\t\t\t\t\t\tval = 'DEFAULT';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(row.DESC_CN!=null){\r\n");
      out.write("\t\t\t\t\t\treturn row.DESC_CN\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn val;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'NO_WAVE1_MIN',\r\n");
      out.write("\t\t\t\ttitle : 'WBP',\r\n");
      out.write("\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\treturn val+\"--\"+row.NO_WAVE1_MAX;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'NO_WAVE1_LAST_USED_ID',\r\n");
      out.write("\t\t\t\ttitle : 'WBP_LAST',\r\n");
      out.write("\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'WAVE1_MIN',\r\n");
      out.write("\t\t\t\ttitle : 'CSSS',\r\n");
      out.write("\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\treturn val+\"--\"+row.WAVE1_MAX;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'WAVE1_LAST_USED_ID',\r\n");
      out.write("\t\t\t\ttitle : 'CSSS_LAST',\r\n");
      out.write("\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'ISDELETE',\r\n");
      out.write("\t\t\t\ttitle : 'STATUS',\r\n");
      out.write("\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\tformatter:function(val,row){\r\n");
      out.write("\t\t\t\t\tif(val==1){\r\n");
      out.write("\t\t\t\t\t\treturn \"Locked\";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn \"Active\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t} ] ],\r\n");
      out.write("\t\t\tonLoadSuccess : function() {\r\n");
      out.write("\t\t\t\t$(\"#mDefaultdiv\").dialog(\"open\");\r\n");
      out.write("\t\t\t\t$(\"#acc\").accordion(\"select\",1);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonSelect: function(index,row){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tonClickRow : function(rowIndex, rowData) {\r\n");
      out.write("\t\t\t\t$(\"#defaultlist\").datagrid(\"unselectRow\",rowIndex);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 点击按钮后执行的操作 */\r\n");
      out.write("\tfunction dotoolbar(type){\r\n");
      out.write("\t\tvar lists = $(\"#defaultlist\").datagrid(\"getSelections\");//获取选中的列表\r\n");
      out.write("\t\tif(lists == 0){\r\n");
      out.write("\t\t\t$.messager.alert(\"Message\",'Please Check One Data');\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(type==\"edit\"){//编辑操作\r\n");
      out.write("\t\t\tfor(var j=0;j<lists.length;j++){\r\n");
      out.write("\t\t\t\tif(lists[j].ISDELETE==1){\r\n");
      out.write("\t\t\t\t\tcontinue;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar code = lists[j].CODE;\r\n");
      out.write("\t\t\t\tif($('#'+code+'editid').length>0){\r\n");
      out.write("\t\t\t\t\tcontinue;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t    addnumberbox(code);//添加一行编辑\r\n");
      out.write("\t\t\t    loadnumberbox(code,lists[j]);//填充数值\r\n");
      out.write("\t\t\t\ti++;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$(\"#defaultlist\").datagrid(\"uncheckAll\");\r\n");
      out.write("\t\t} else {//删除操作\r\n");
      out.write("\t\t\t$.messager.confirm('Confirm', 'Are you sure Remove?', function(r){//删除前进行提示\r\n");
      out.write("\t\t\t\tif (r){\r\n");
      out.write("\t\t\t\t\tvar ids= \"\";\r\n");
      out.write("\t\t\t\t\tfor(var j=0 ; j<lists.length ; j++){\r\n");
      out.write("\t\t\t\t\t\tids += lists[j].ID + \",\";\r\n");
      out.write("\t\t\t\t\t\tvar code = lists[j].CODE;\r\n");
      out.write("\t\t\t\t\t\tif(code == 'default'){//不能删除default\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert(\"Deleting default value is unallowed !\");\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(lists[j].ISDELETE == '1'){//不能删除已删除的\r\n");
      out.write("\t\t\t\t\t\t\t$.messager.alert(\"Deleted value can't re-delete !\");\r\n");
      out.write("\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t$('#'+code+'editid').parent().parent().remove();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(ids != \"\"){\r\n");
      out.write("\t\t\t\t\t\tids = ids.substring(0 , ids.length - 1);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$.ajax({//提交后台删除\r\n");
      out.write("\t\t\t           url: \"");
      out.print(request.getContextPath() );
      out.write("/RangeDetail.do?ids=\" + ids,\r\n");
      out.write("\t\t\t           method: \"DELETE\",\r\n");
      out.write("\t\t\t           success: function(){\r\n");
      out.write("\t\t\t        \t\tchangecheck();\r\n");
      out.write("\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tif($(\"#edittable tbody\").html()==\"\"){\r\n");
      out.write("\t\t\t\t\t\t$(\"#edittable tbody\").html(\"\");\r\n");
      out.write("\t\t\t\t\t\twindow.top.isexitfn(false);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 加载编辑区域的input*/\r\n");
      out.write("\tfunction addnumberbox(code){\r\n");
      out.write("\t\t$(\"#edittable\").append(\"<tr class='tr\"+i+\"'><td><input type='hidden' id='\"+code+\"editid' name='\"+code+\"editid'/><span id='\"+code+\"show' name='\"+code+\"show'></span><input type='hidden' name='codes' value='\"+code+\"'  style='width:60px' readonly /></td><td><input id='\"+code+\"nowavemin' name='\"+code+\"nowavemin' code='\"+code+\"' class='easyui-numberbox numbox' data-options='min:\"+nowavemin+\",max:\"+nowavemax+\",precision:0,required:true'></td><td><input id='\"+code+\"nowavemax' name='\"+code+\"nowavemax' class='easyui-numberbox numbox' code='\"+code+\"' data-options='min:\"+nowavemin+\",max:\"+nowavemax+\",precision:0,required:true'/></td><td><input id='\"+code+\"nowavelast' name='\"+code+\"nowavelast' class='easyui-numberbox numbox' code='\"+code+\"' data-options='min:\"+nowavemin+\",max:\"+nowavemax+\",precision:0,required:true'/></td><td><input id='\"+code+\"wavemin' name='\"+code+\"wavemin' code='\"+code+\"' class='easyui-numberbox numbox' data-options='min:\"+wavemin+\",max:\"+wavemax+\",precision:0,required:true'></td><td><input id='\"+code+\"wavemax' name='\"+code+\"wavemax' code='\"+code+\"' class='easyui-numberbox numbox' data-options='min:\"+wavemin+\",max:\"+wavemax+\",precision:0,required:true'></td><td><input id='\"+code+\"wavelast' name='\"+code+\"wavelast' code='\"+code+\"' class='easyui-numberbox numbox' data-options='min:\"+wavemin+\",max:\"+wavemax+\",precision:0,required:true'></td><td><button class='linkbuttons' onclick=removetr('tr\"+i+\"')>-</button></td></tr>\");\r\n");
      out.write("\t\t$(\".numbox\").numberbox({//将input变为只能输入数字的input\r\n");
      out.write("\t\t\twidth:'130px',\r\n");
      out.write("\t\t\theight:'28px',\r\n");
      out.write("\t\t\tonChange:function(newValue,oldValue){\r\n");
      out.write("\t\t\t\t//check(newValue);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#\"+code+\"wavemin\").numberbox({\r\n");
      out.write("\t\t\tonChange:function(newValue,oldValue){\r\n");
      out.write("\t\t\t\tif($(\"#\"+code+\"wavelast\").numberbox(\"getValue\")==\"\"){\r\n");
      out.write("\t\t\t\t\t$(\"#\"+code+\"wavelast\").numberbox(\"setValue\",newValue)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#\"+code+\"nowavemin\").numberbox({\r\n");
      out.write("\t\t\tonChange:function(newValue,oldValue){\r\n");
      out.write("\t\t\t\tif($(\"#\"+code+\"nowavelast\").numberbox(\"getValue\")==\"\"){\r\n");
      out.write("\t\t\t\t\t$(\"#\"+code+\"nowavelast\").numberbox(\"setValue\",newValue)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".easyui-numberbox\").numberbox(\"disableValidation\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 将已有的值则将值加入input中 */\r\n");
      out.write("\tfunction loadnumberbox(code,data){\r\n");
      out.write("\t\t\tvar show = data.DESC_CN==null?data.CODE:data.DESC_CN;\r\n");
      out.write("\t\t\t$(\"#\"+code+\"show\").html(show);\r\n");
      out.write("\t\t\t$(\"#\"+code+\"wavemax\").numberbox(\"setValue\",data.WAVE1_MAX);//wbp最大范围\r\n");
      out.write("\t\t\t$(\"#\"+code+\"wavemin\").numberbox(\"setValue\",data.WAVE1_MIN);//wbp最小范围\r\n");
      out.write("\t\t\t$(\"#\"+code+\"nowavemin\").numberbox(\"setValue\",data.NO_WAVE1_MIN);//CSSS最大范围\r\n");
      out.write("\t\t\t$(\"#\"+code+\"nowavemax\").numberbox(\"setValue\",data.NO_WAVE1_MAX);//CSSS最小范围\r\n");
      out.write("\t\t\t$(\"#\"+code+\"wavelast\").numberbox(\"setValue\",data.WAVE1_LAST_USED_ID);//wbp当前值\r\n");
      out.write("\t\t\t$(\"#\"+code+\"nowavelast\").numberbox(\"setValue\",data.NO_WAVE1_LAST_USED_ID);//csss当前值\r\n");
      out.write("\t\t\t$(\"#\"+code+\"editid\").val(data.ID);//编辑数据的code\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//添加一行编辑记录(type 编辑的类型)\r\n");
      out.write("\tvar i=0;\r\n");
      out.write("\tfunction addtr(type){\r\n");
      out.write("\t\tvar code = \"\";\r\n");
      out.write("\t\tif(type==\"location\"){\r\n");
      out.write("\t\t\tvar code = $('#location').combobox(\"getValue\");\r\n");
      out.write("\t\t\t$('#location').combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t} else if(type==\"bp\") {\r\n");
      out.write("\t\t\tcode = $('#bp').combobox(\"getValue\");\r\n");
      out.write("\t\t} else if(type==\"orign\") {\r\n");
      out.write("\t\t\tcode = $('#orign').combobox(\"getValue\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(code == \"\" || code == \" \" || !code){\r\n");
      out.write("\t\t\t$.messager.alert(\"Error\",\"Plese Select a data\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif($('#'+code+'editid').length>0){\r\n");
      out.write("\t\t\t$.messager.alert(\"Error\",\"The Data has already edited\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\taddnumberbox(code);//在编辑区加载出input框\r\n");
      out.write("\t\tloadData(code,type);//为input框填充已有数据\r\n");
      out.write("\t\twindow.top.isexitfn(true);\r\n");
      out.write("\t\ti++;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//第一次进行编辑时必须对默认default进行编辑\r\n");
      out.write("\tfunction iseditdefault(){\r\n");
      out.write("\t\tvar data = $(\"#defaultlist\").datagrid(\"getData\").rows;\r\n");
      out.write("\t\tif(data.length == 1 && data[0].CODE == \"default\"){\r\n");
      out.write("\t\t\tif($('#defaulteditid').length==0){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 读取后台数据用于加载 code:用于读取后台信息的key type:读取的类型(location、booking party、orign)*/\r\n");
      out.write("\tfunction loadData(code,type){\r\n");
      out.write("\t\tif(type == \"location\"){\r\n");
      out.write("\t\t\t$.ajax({            \r\n");
      out.write("\t\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/ManagerServlet?action=loadlocation&code=\"+code,\r\n");
      out.write("\t\t\t\tmethod: \"GET\",            \r\n");
      out.write("\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t  \t\tfor(var i=0;i<data.rows.length;i++){\r\n");
      out.write("\t\t\t  \t\t\tif(data.rows[i].CODE!=\"default\"){\r\n");
      out.write("\t\t\t  \t\t\t\tloadnumberbox(code,data.rows[i]);\r\n");
      out.write("\t\t\t  \t\t\t}\r\n");
      out.write("\t\t\t  \t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else if(type == \"bp\") {\r\n");
      out.write("\t\t\t$.ajax({            \r\n");
      out.write("\t\t\t\turl: \"");
      out.print(request.getContextPath());
      out.write("/BusinessPartner.do\",\r\n");
      out.write("\t\t\t\tmethod:'GET',\r\n");
      out.write("\t\t        dataType:\"json\",\r\n");
      out.write("\t\t\t\tdata: { \"code\" : code },  \r\n");
      out.write("\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tif(data.rows.length == 0){\r\n");
      out.write("\t\t\t\t\t\tvar show = $('#bp').combobox(\"getText\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+code+\"show\").html(show);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t  \t\tfor(var i=0;i<data.rows.length;i++){\r\n");
      out.write("\t\t\t  \t\t\tif(data.rows[i].CODE!=\"default\"){\r\n");
      out.write("\t\t\t  \t\t\t\tloadnumberbox(code,data.rows[i]);\r\n");
      out.write("\t\t\t  \t\t\t}\r\n");
      out.write("\t\t\t  \t\t}\r\n");
      out.write("\t\t\t  \t\t$('#bp').combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t} else if(type == \"orign\") {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl: \"");
      out.print(request.getContextPath() );
      out.write("/Origin.do\",\r\n");
      out.write("\t\t\t\tmethod: 'GET',\r\n");
      out.write("\t\t\t\tdata : { \"code\": code , \"parentId\" : parentid },\r\n");
      out.write("\t\t\t\tdataType: \"json\",\r\n");
      out.write("\t\t\t\tasync: false,\r\n");
      out.write("\t\t\t\tsuccess: function(data) {\r\n");
      out.write("\t\t\t\t\tif(data.rows.length==0){\r\n");
      out.write("\t\t\t\t\t\tvar show = $('#orign').combobox(\"getText\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#\"+code+\"show\").html(show);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t  \t\tfor(var i=0;i<data.rows.length;i++){\r\n");
      out.write("\t\t\t  \t\t\tloadnumberbox(code,data.rows[i]);\r\n");
      out.write("\t\t\t  \t\t}\r\n");
      out.write("\t\t\t  \t\t$('#orign').combobox(\"setValue\",\"\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 提交数据 */\r\n");
      out.write("\tfunction sub(){\r\n");
      out.write("\t\tif($(\"#edittable tbody\").html()!=\"\"){//判断是否有待保存数据\r\n");
      out.write("\t\t\tif(iseditdefault()){//判断在首次编辑时是有对default进行编辑动作\r\n");
      out.write("\t\t\t\t$.messager.confirm('Confirm', 'Are you sure Submit?', function(r){\r\n");
      out.write("\t\t\t\t\tif (r){\r\n");
      out.write("\t\t\t\t\t\t$(\"#form1\").submit();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}else{//没有对default进行编辑动作提示不做提交\r\n");
      out.write("\t\t\t\t$.messager.alert(\"Error\",\"first adding new record must change default value,please click default row and edit it!\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.messager.alert(\"Error\",\"No Edited data\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 移除编辑的行 id:行的id编号 */\r\n");
      out.write("\tfunction removetr(id){\r\n");
      out.write("\t\t$(\".\"+id).remove();\r\n");
      out.write("\t\tif($(\"#edittable tbody\").html()==\"\"){\r\n");
      out.write("\t\t\t$(\"#edittable tbody\").html(\"\");\r\n");
      out.write("\t\t\twindow.top.isexitfn(false);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t/* 不进行编辑，返回操作 */\r\n");
      out.write("\tfunction back(){\r\n");
      out.write("\t\tif($(\"#edittable tbody\").html()==\"\"){\r\n");
      out.write("\t\t\tlocation.href=\"rangeInfo.jsp\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.messager.confirm('Confirm', 'Are you sure to exit the editor?', function(r){\r\n");
      out.write("\t\t\t\tif (r){\r\n");
      out.write("\t\t\t\t\tlocation.href=\"rangeInfo.jsp\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
